--- #YAML:1.0
name:                WebService-MusicBrainz
version:             0.04
abstract:            Interface to MusicBrainz web service
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Accessor:               0
    LWP::UserAgent:                2
    XML::Twig:                     3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Bob Faist <bob.faist@gmail.com>
