# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-MusicBrainz
version:      0.03
version_from: lib/WebService/MusicBrainz/Query.pm
installdirs:  site
requires:
    Class::Accessor:               0
    LWP::UserAgent:                2
    XML::Twig:                     3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
